name: First Workflow
on: 
  push: 
  workflow_dispatch:
  pull_request:
    branches: 
      - main
      - "dev-*"
    paths-ignore:
      - ".github/workflows/*"

jobs:
  PR-Verification:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - uses: actions/setup-python@v5 
      with:
        python-version: '3.12' 

    - name: Install dependencies
      run: |
        poetry install -v

    - name: Black formatting check
      run: |
        poetry run black --check .

    - name: Isort check
      run: |
        poetry run isort --check .

    - name: Unit tests
      run: |
        poetry run pytest -v > test_results.txt
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: Pytest-results
        path: test_results.txt

  Build:
    needs: PR-Verification
    runs-on: ubuntu-latest
    outputs:
      build_output: ${{ steps.set_output.outputs.build_result }}

    steps:
    - name: Pretend to build
      id: set_output
      run: |
        echo "Building the project"
        echo "::set-output name=build_result::successful"

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Pretend to deploy
      run: echo "Deploying the project"
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: Pytest-results
        path: test_results.txt
    - name: List results
      run: |
        ls -als
        cat test_results.txt
        echo "The build result was: ${{ needs.Build.outputs.build_output }}"