name: First Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Run tests
      run: poetry run pytest -v
    - name: Install dependencies
      run: poetry install -v