name: First Workflow
on: push
jobs:
  PR-Verification:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
      
    - uses: actions/setup-python@v5 
      with:
        python-version: '3.12' 
    
    - name: Install dependencies
      run: |
        poetry install -v
    
    - name: Unit tests
      run: |
        poetry run pytest -v
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Pretend to build
      run: echo "Building the project"