name: First Workflow
on: 
  push: 
  workflow_dispatch:
  pull_request:
    branches: 
      - main
      - "dev-*"
    paths-ignore:
      - ".github/workflows/*"

jobs:
  PR-Verification:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - uses: actions/setup-python@v5 
      with:
        python-version: '3.12' 

    - name: Install dependencies
      run: |
        poetry install -v

    - name: Black formatting check
      run: |
        poetry run black --check .

    - name: Isort check
      run: |
        poetry run isort --check .

    - name: Unit tests
      run: |
        poetry run pytest -v

  Build:
    needs: PR-Verification
    runs-on: ubuntu-latest
    steps:
    - name: Pretend to build
      run: echo "Building the project"

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Pretend to deploy
      run: echo "Deploying the project"